Unfinished controller support, please follow comments
HasangerGames/suroi pull request #376
Opened 2024-09-15 00:04 UTC by Arman-AIi

note: this has only been tested on stadia controller

2024-09-15 02:36 UTC, Compositr reviewed
Is there any way to do this without having a ton of gamepadX or whatever vars?

2024-09-15 02:40 UTC, Arman-AIi commented
You can condense them into a few lines but you need them to use all controller buttons

2024-09-15 05:09 UTC, tomatopotato17265 commented
Controls recommendations:

B: drop items (press to scroll between items, press and hold to actually drop)
X: map
Y: Special emotes (ammo request, medkit request, etc.)

idk how this works but if you can take advantage of the mini-touchpad on ps4 and ps5 controllers for a mini cursor some ppl might like that

2024-09-15 16:18 UTC, Arman-AIi commented
> Controls recommendations:
> 
> B: drop items (press to scroll between items, press and hold to actually drop) X: map Y: Special emotes (ammo request, medkit request, etc.)
> 
> idk how this works but if you can take advantage of the mini-touchpad on ps4 and ps5 controllers for a mini cursor some ppl might like that

how will Y for special emotes work exactly

2024-09-15 18:23 UTC, tomatopotato17265 commented
> > Controls recommendations:
> 
> > 
> 
> > B: drop items (press to scroll between items, press and hold to actually drop) X: map Y: Special emotes (ammo request, medkit request, etc.)
> 
> > 
> 
> > idk how this works but if you can take advantage of the mini-touchpad on ps4 and ps5 controllers for a mini cursor some ppl might like that
> 
> 
> 
> how will Y for special emotes work exactly

You hold down Y while using the D-pad. This system works similar to mobile special emotes: you toggle that cellular tower thing then select the emotes.

2024-09-15 18:40 UTC, Arman-AIi commented
> > > Controls recommendations:
> > 
> > 
> > > 
> > 
> > 
> > > B: drop items (press to scroll between items, press and hold to actually drop) X: map Y: Special emotes (ammo request, medkit request, etc.)
> > 
> > 
> > > 
> > 
> > 
> > > idk how this works but if you can take advantage of the mini-touchpad on ps4 and ps5 controllers for a mini cursor some ppl might like that
> > 
> > 
> > how will Y for special emotes work exactly
> 
> You hold down Y while using the D-pad. This system works similar to mobile special emotes: you toggle that cellular tower thing then select the emotes.

Sounds good. The primary goal is to have bindable controller buttons and working analog sticks, defaults are just a nice-to-have. We also must have a controller-navigable UI

2024-09-21 04:12 UTC, tomatopotato17265 commented
> > > > Controls recommendations:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > B: drop items (press to scroll between items, press and hold to actually drop) X: map Y: Special emotes (ammo request, medkit request, etc.)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > idk how this works but if you can take advantage of the mini-touchpad on ps4 and ps5 controllers for a mini cursor some ppl might like that
> 
> > > 
> 
> > > 
> 
> > > how will Y for special emotes work exactly
> 
> > 
> 
> > You hold down Y while using the D-pad. This system works similar to mobile special emotes: you toggle that cellular tower thing then select the emotes.
> 
> 
> 
> Sounds good. The primary goal is to have bindable controller buttons and working analog sticks, defaults are just a nice-to-have. We also must have a controller-navigable UI

We should take things one at a time. Suroi for console doesn't exist yet so we don't need to worry about controller-navigable UI. I say we first add the functionality with default controls, then add the ability to customized bindings. Controller-navigable UI is something we don't have to worry about until we make Suroi for Xbox, PlayStation, Nintendo Switch, or other controller-based platform.

2024-09-21 21:47 UTC, kenos1 commented
this easily has to be one of the most atrocious pieces of code i've ever seen from a suroi dev

how hard is it to not repeat yourself and do something like

```js
const GamepadButtonMap = ["GamepadA", ...] // truncated for demo purposes

if (event instanceof GamepadEvent) {
  input = GamepadButtonMap.find((_, i) => event.gamepad.buttons[i].pressed) ?? "GamepadUnknown"
}
```

2024-09-21 21:49 UTC, kenos1 commented on client/src/scripts/managers/inputManager.ts
> +function gameLoop(){
me when PIXI.Application.ticker

2024-09-21 21:50 UTC, Compositr requested changes
We need to make this far, far more concise. Also what the hell is that gameLoop function... (see Kenos' comment)

2024-09-21 21:55 UTC, kenos1 commented
Also please read https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/buttons as you are missing critical information lol

2024-09-21 22:02 UTC, kenos1 approved these changes
oh yeah by the way to anyone whos reading patch-notes channel i am homeless and also the fbi is after me

2024-09-21 22:02 UTC, kenos1 commented on client/src/scripts/managers/inputManager.ts
>  import { getTranslatedString } from "../../translations";
oh yeah by the way to anyone whos reading patch-notes channel i am homeless and also the fbi is after me

2024-09-21 22:03 UTC, Arman-AIi commented
> Also please read https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/buttons as you are missing critical information lol

This is the guide I am using

2024-09-21 22:16 UTC, leia-uwu approved these changes
hiiii suroi patch-notes channel I'm totally original and not copying kenos
anyways LGTM should merge asap and push to production :+1:

2024-09-21 22:16 UTC, Arman-AIi commented
> hiiii suroi patch-notes channel I'm totally original and not copying kenos anyways LGTM should merge asap and push to production 👍

I agree with this information

2024-09-21 22:34 UTC, Arman-AIi commented
> We need to make this far, far more concise. Also what the hell is that gameLoop function... (see Kenos' comment)

The requested changes have been fully completed sir.


also how did I wake up leia and kenos 💀 💀

2024-09-21 22:47 UTC, leia-uwu commented
> also how did I wake up leia and kenos 💀 💀

kenos pinged me to make fun of your code

2024-09-21 22:59 UTC, ei-pi commented on client/src/scripts/managers/inputManager.ts
> +            gameLoop();
kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill

2024-09-21 23:00 UTC, 1092384 commented
> You can condense them into a few lines but you need them to use all controller buttons

i've decided you're a furry

2024-09-21 23:01 UTC, kenos1 commented
![image](https://github.com/user-attachments/assets/ec6c3858-deb2-499f-9393-d4511b513433)

2024-09-21 23:09 UTC, Arman-AIi commented
I already changed it why so mean 😢

2024-09-22 02:48 UTC, tomatopotato17265 reviewed
While you're decluttering the code, pls add comments for noobs like me :)

2024-09-22 07:07 UTC, ersek-huba commented
This is the funniest PR comment section, I've ever seen so far (after the Chinese John Cena one (including the Linux PR)).

2024-09-22 17:25 UTC, Arman-AIi commented
new commit, fixed issue where the buttons just refused to register, working and tested

2024-09-23 18:34 UTC, closed without merging